[package]
name = "noiseexplorer_ix_wasm"
version = "1.0.1"
authors = ["Symbolic Software <georgio@symbolic.software>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
blake2-rfc = "0.2.18"
constant_time_eq = "0.1.3"
chacha20-poly1305-aead = {version = "0.1.2", git = "https://github.com/georgio/chacha20-poly1305-aead"}
getrandom = "0.1.3"
hex = "0.3.2"
rust-crypto-wasm = "0.3.1"
zeroize = "0.6.0"
wasm-bindgen = "0.2.46"
js-sys = "0.3"
once_cell = "1.4.0"
thiserror = "1.0"

[dependencies.web-sys]
version = "0.3.45"
features = [
    "Window",
    "Crypto",
    "BinaryType",
    "Blob",
    "ErrorEvent",
    "FileReader",
    "MessageEvent",
    "ProgressEvent",
    "WebSocket",
]

[dev-dependencies]
wasm-bindgen-test = "0.2"

[package.metadata.wasm-pack.profile.dev.wasm-bindgen]
debug-js-glue = true
demangle-name-section = true
dwarf-debug-info = false

[package.metadata.wasm-pack.profile.profiling.wasm-bindgen]
debug-js-glue = false
demangle-name-section = true
dwarf-debug-info = false

[package.metadata.wasm-pack.profile.release.wasm-bindgen]
debug-js-glue = false
demangle-name-section = true
dwarf-debug-info = false

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-Oz", "--enable-mutable-globals"]