[package]
name = "node-neon"
version = "0.1.0"
authors = ["IOTA Stiftung"]
license = "MIT"
build = "build.rs"
edition = "2018"
exclude = ["artifacts.json", "index.node"]

[lib]
name = "node_neon"
crate-type = ["cdylib"]

[build-dependencies]
neon-build = "0.10.1"

[dependencies]
iota-wallet = { git = "https://github.com/iotaledger/wallet.rs", branch = "firefly-desktop", default-features = false, features = ["stronghold", "ledger-nano", "ledger-nano-simulator", "participation"] }
futures = { version = "0.3.17", default-features = false }
neon = "0.10.1"
serde_json = { version = "1.0.68", default-features = false }
tokio = { version = "1.28.0", default-features = false }
once_cell = { version = "1.8.0", default-features = false }
firefly-actor-system = { path = "../../.." }

[profile.release]
# Build with debug symbols included
debug = true
