[package]
name = "node-neon"
version = "0.1.0"
authors = ["IOTA Stiftung"]
license = "MIT"
build = "build.rs"
edition = "2018"
exclude = ["artifacts.json", "index.node"]

[lib]
name = "node_neon"
crate-type = ["cdylib"]

[build-dependencies]
neon-build = "0.10.1"

[dependencies]
futures = { version = "0.3.17", default-features = false }
neon = "0.10.1"
serde_json = { version = "1.0.68", default-features = false }
tokio = { version = "1.28.0", default-features = false }
once_cell = { version = "1.8.0", default-features = false }
firefly-actor-system = { path = "../../.." }

[package.metadata.patch.neon-sys]
version = "0.10.1"
patches = [
    { path = "neon_temp_buf.patch", source = "GithubPrDiff" },
]

[patch.crates-io]
neon-sys = { path = './target/patch/neon-sys-0.10.1' }

[profile.release]
# Build with debug symbols included
debug = true
