[package]
name = "wallet-actor-system"
version = "0.1.0"
authors = ["Lucas Nogueira <lucas.nogueira@iota.org>"]
edition = "2018"
exclude = ["/bindings", "/api-wrapper"]

[dependencies]
tokio = { version = "1.1", features = ["full"] }
once_cell = "1.5.0"
iota-wallet = { git = "https://github.com/iotaledger/wallet.rs", branch = "migration", default-features = false, features = ["stronghold"] }
serde_json = "1.0"
riker = "0.4"
serde = "1.0"
iota-core = { git = "https://github.com/iotaledger/iota.rs", branch = "dev" }
log = "0.4"

[dev-dependencies]
futures = "0.3"
