[package]
name = "firefly-actor-system"
version = "0.1.0"
authors = ["IOTA Stiftung"]
edition = "2018"
exclude = ["/bindings", "/api-wrapper"]

[dependencies]
tokio = { version = "1.12.0", default-features = false }
once_cell = { version = "1.8.0", default-features = false }

# iota-wallet = { git = "https://github.com/iotaledger/wallet.rs", rev = "f21eb3ced89d90ea77e4797e32c0ddc22577687b", default-features = false, features = ["stronghold", "ledger-nano", "ledger-nano-simulator", "participation"] }
iota-wallet = { git = "ssh://git@github.com/thibault-martinez/wallet.rs-private", branch = "stronghold-fix-base-d773dc", default-features = false, features = ["stronghold", "ledger-nano", "ledger-nano-simulator", "participation"] }
serde = { version = "1.0.130", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.68", default-features = false }
riker = "0.4.2"
bee-common = { version = "0.4.1", default-features = false }
log = { version = "0.4.14", default-features = false }
sentry = { version = "0.24.3", default-features = false, features = ["backtrace", "contexts", "panic", "reqwest", "rustls"] }

[dev-dependencies]
futures = "0.3"
