[package]
name = "wallet-actor-system"
version = "0.1.0"
authors = ["IOTA Stiftung"]
edition = "2018"
exclude = ["/bindings", "/api-wrapper"]

[dependencies]
bee-common = { version = "0.4.1", default-features = false }
iota-wallet = { git = "https://github.com/iotaledger/wallet.rs", rev = "0c8320f9d4a09224966d7ccae2e86a7b591442bd", default-features = false, features = ["stronghold", "ledger-nano", "ledger-nano-simulator"] }
log = { version = "0.4.14", default-features = false }
once_cell = { version = "1.8.0", default-features = false }
serde = { version = "1.0.130", default-features = false }
serde_json = { version = "1.0.68", default-features = false }
tokio = { version = "1.12.0", default-features = false }
riker = { version = "0.4.2", default-features = false }

[dev-dependencies]
futures = "0.3"
