[package]
name = "firefly-actor-system"
version = "0.1.0"
authors = ["IOTA Stiftung"]
edition = "2018"
exclude = ["/bindings", "/api-wrapper"]

[dependencies]
tokio = { version = "1.28.0", default-features = false }
once_cell = { version = "1.8.0", default-features = false }

iota-wallet = { git = "https://github.com/iotaledger/wallet.rs", rev = "ebcbc04319d11ec973da5d8d6d775e54577f116d", default-features = false, features = ["stronghold", "ledger-nano", "ledger-nano-simulator", "participation"] }
serde = { version = "1.0.130", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.68", default-features = false }
riker = "0.4.2"
bee-common = { version = "0.4.1", default-features = false }
log = { version = "0.4.14", default-features = false }
sentry = { version = "0.24.3", default-features = false, features = ["backtrace", "contexts", "panic", "reqwest", "rustls"] }

[dev-dependencies]
futures = "0.3"
