name: pr-checks

on:
  push:
    branches:
      - chore/**
      - fix/**
      - feat/**
      - hotfix/**

jobs:
  lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: Install Dependencies
        run: yarn

      - name: Linter (Backend)
        run: yarn lint:backend

      - name: Linter (Desktop)
        run: yarn lint:desktop

      - name: Linter (Mobile)
        run: yarn lint:mobile

      - name: Linter (Shared)
        run: yarn lint:shared

  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: See Directories
        run: pwd && ls

      - name: Install Dependencies
        working-directory: packages/shared
        run: yarn

      - name: Test
        working-directory: packages/shared
        run: yarn test
